### PR TITLE
Add .ackrc

### PR DESCRIPTION
**Pull request by fawkesley**

### CODE REVIEW

**Comment by Demotive** [comment]
Wait, this shouldn't be in the repo?

**Comment by fawkesley** [comment]
@evilstreak and I had a debate about this and I agree in principle.

As an alternative solution, would y'all accept putting `.ackrc` in `.gitignore` ?

**Comment by Demotive** [comment]
That works for me... @evilstreak ?

**Comment by evilstreak** [comment]
Having just checked, it turns out I have `.ackrc` in my global `.gitignore`. That said, I wouldn't massively object to it being in a project specific `.gitignore`.

**Comment by fawkesley** [comment]
@evilstreak Now I've actually got that working (for me it's `~/.config/git/ignore`), that's a good solution.

**Pull request closed without merging**
